-- Assigned to John, created by John 
INSERT INTO ToDo (ACTION,ASSIGNEDTO_ID,CREATEDBY_ID,CREATED,UPDATEDBY_ID,UPDATED) VALUES ('Buy milk',1,1,CURRENT_TIMESTAMP,1,CURRENT_TIMESTAMP);

-- Assigned to Jane, created by John
INSERT INTO ToDo (ACTION,ASSIGNEDTO_ID,CREATEDBY_ID,CREATED,UPDATEDBY_ID,UPDATED) VALUES ('Buy soy sauce',2,1,CURRENT_TIMESTAMP,1,CURRENT_TIMESTAMP);

-- Assigned to Jane, created by Jane
INSERT INTO ToDo (ACTION,ASSIGNEDTO_ID,CREATEDBY_ID,CREATED,UPDATEDBY_ID,UPDATED) VALUES ('Buy soy sauce',2,1,CURRENT_TIMESTAMP,1,CURRENT_TIMESTAMP);

-- Assigned to John, created by Jane
INSERT INTO ToDo (ACTION,ASSIGNEDTO_ID,CREATEDBY_ID,CREATED,UPDATEDBY_ID,UPDATED) VALUES ('Buy soy sauce',2,1,CURRENT_TIMESTAMP,1,CURRENT_TIMESTAMP);